title: Simon's Control Centre
description: Everything in one place?

theme: just-the-docs
color_scheme: cockell

url: https://sjcockell.github.io/control-centre

aux_links:
  GitHub: https://github.com/sjcockell
