title: Simon's Control Centre
description: Everything in one place?

theme: just-the-docs
color_scheme: dark

url: https://sjcockell.github.io
baseurl: /control-centre

aux_links:
  GitHub: https://github.com/sjcockell
