title: Prof SJ Cockell Control Centre
description: Everything in one place?
theme: just-the-docs

url: https://sjcockell.github.io/control-centre
color_scheme: dark

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
